[[constraint]]
  name = "github.com/drone/drone-go"
  branch = "master"

[[constraint]]
  name = "github.com/hashicorp/terraform"
  version = "0.11.7"

[[constraint]]
  branch = "master"
  name = "golang.org/x/oauth2"
